### ISSUE TITLE
Integration V3: error is thrown while indexing complete content with SOLR5

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#415]
Auf sb-s4 ist der Solr5 Index für Basel / Bern zur Benutzung durch vufind - swissbib basierend auf Vufind V3 aufgesetzt.
Während ich den Index mit dem letzten Export (Februar 2016) auf sb-s12 neu aufgesetzt habe, ist mir eine eine Fehlermeldung afgefallen, die gelegentlch auftrit (s.u)

Dies kann mit diesem Thread zusammenhängen. 
https://issues.apache.org/jira/browse/SOLR-4146
s.auch: http://www.gossamer-threads.com/lists/lucene/java-dev/301347
Wir sollten das im Auge behalten

2016-04-12 14:21:11.020 INFO  (qtp59559151-44) [   x:sb_biblio] o.a.s.u.p.LogUpdateProcessorFactory [sb_biblio]  webapp=/solr path=
/update params={}{add=[114492816 (1531414700376457216), 114492824 (1531414700384845824), 114492859 (1531414700385894400), 114492867
 (1531414700386942976), 114492883 (1531414700387991552), 114492891 (1531414700389040128), 114492905 (1531414700389040129), 11449291
3 (1531414700394283008), 114492921 (1531414700394283009), 11449293X (1531414700402671616), ... (1000 adds)]} 0 3504
2016-04-12 14:21:11.315 ERROR (qtp59559151-18) [   x:sb_biblio] o.a.s.h.RequestHandlerBase java.nio.file.NoSuchFileException: /swis
sbib_index/solrIndexBiblio/noDocValues/index/segments_61
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.Files.size(Files.java:2332)
        at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:210)
        at org.apache.lucene.store.NRTCachingDirectory.fileLength(NRTCachingDirectory.java:127)
        at org.apache.solr.handler.admin.LukeRequestHandler.getIndexInfo(LukeRequestHandler.java:592)
        at org.apache.solr.handler.admin.LukeRequestHandler.handleRequestBody(LukeRequestHandler.java:137)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2082)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:670)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:458)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:225)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:183)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

**Comment by guenterh** [comment]
wir machen mit Solr 5 nichts mehr
@sonjakupfi - bitte in Trello schliessen
