### ISSUE TITLE
Routing Fehler jus advanced search PHP7

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#449]
auf develop.swissbib.ch führt der Request 
https://develop.swissbib.ch/Search/Advanced
zu einem Routing Fehler
Message: Route with name "search-advancedClassification" not found 

#0 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/View/Helper/Url.php(100): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#1 /usr/local/vufind/httpd/module/VuFind/src/VuFind/View/Helper/Root/SearchTabs.php(345): Zend\View\Helper\Url->__invoke('search-advanced...')
#2 /usr/local/vufind/httpd/module/VuFind/src/VuFind/View/Helper/Root/SearchTabs.php(134): VuFind\View\Helper\Root\SearchTabs->createAdvancedTab('SolrClassificat...', 'SolrClassificat...', 'classification_...', Array)
#3 /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/VuFind/View/Helper/Root/SearchTabs.php(89): VuFind\View\Helper\Root\SearchTabs->getTabConfig('Solr', NULL, NULL, 'advanced')
#4 /usr/local/vufind/httpd/themes/sbvfrdjus/templates/search/advanced/layout.phtml(52): Swissbib\VuFind\View\Helper\Root\SearchTabs->getTabConfig('Solr', NULL, NULL, 'advanced', Array, 'advanced')
#5 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(501): include('/usr/local/vufi...')
#6 /usr/local/vufind/httpd/themes/bootstrap3/templates/search/advanced.phtml(5): Zend\View\Renderer\PhpRenderer->render()
#7 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(501): include('/usr/local/vufi...')
#8 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/View/View.php(205): Zend\View\Renderer\PhpRenderer->render()
#9 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/View/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#10 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/View/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#11 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Mvc/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#12 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#13 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#15 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(353): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#16 /usr/local/vufind/httpd/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(328): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#17 /usr/local/vufind/httpd/public/index.php(81): Zend\Mvc\Application->run()
#18 {main}

**Comment by guenterh** [comment]
Fehler von mir, ich hatte Jusbib Modul bei mir im Apache nicht aktiviert gehabt
