### ISSUE TITLE
merge core2sb_manually (Änderung der Schnittstelle Search\Solr\Params)

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#497]
@edelm 
Hallo Matthias,
habe soeben nochmals gemerged. Ich bekomme folgenden Fehler:

[Fri Feb 24 12:47:43.269663 2017] [:error] [pid 4664] [client 131.152.212.156:45254] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to VuFind\\Search\\Solr\\Params::__construct() must be an instance of VuFind\\Search\\Solr\\HierarchicalFacetHelper, instance of Swissbib\\Favorites\\Manager given, called in /usr/local/vufind/c2sbm/module/Swissbib/src/Swissbib/VuFind/Search/Params/PluginFactory.php on line 98 and defined in /usr/local/vufind/c2sbm/module/VuFind/src/VuFind/Search/Solr/Params.php:105\nStack trace:\n#0 /usr/local/vufind/c2sbm/module/Swissbib/src/Swissbib/VuFind/Search/Params/PluginFactory.php(98): VuFind\\Search\\Solr\\Params->__construct(Object(Swissbib\\VuFind\\Search\\Solr\\Options), Object(VuFind\\Config\\PluginManager), Object(Swissbib\\Favorites\\Manager))\n#1 [internal function]: Swissbib\\VuFind\\Search\\Params\\PluginFactory->createServiceWithName(Object(Swissbib\\VuFind\\Search\\Params\\PluginManager), 'solr', 'Solr')\n#2 /usr/local/vufind/c2sbm/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(936): call_user_func(Array, Object(Swissbib\\VuFind\\Search\\Params\\PluginManager), 'solr', 'Solr')\n#3 /usr in /usr/local/vufind/c2sbm/module/VuFind/src/VuFind/Search/Solr/Params.php on line 105

Kannst Du es mal ansehen? Danke!

Günter

**Comment by guenterh** [comment]
Behoben mit aktuellen Aktivitäten zur Migration von VF4
