### ISSUE TITLE
cache problem ?

### ISSUE THREAD

**Issue by liowalter** [swissbib/vufind#730]
in the swissbib.error.log of sb-uvf21 :

[Wed Jan 15 10:32:11.339922 2020] [php7:notice] [pid 20802] [client 131.152.34.237:53796] PHP Notice:  Trying to get property 'extendedTargets' of non-object in /usr/local/vufind/httpd/module/Swissbib/src/Swissbib/VuFind/Search/Helper/Factory.php on line 55
[Wed Jan 15 10:32:11.341569 2020] [php7:error] [pid 20802] [client 131.152.34.237:53796] PHP Fatal error:  Uncaught ProxyManager\\Exception\\InvalidProxyDirectoryException: Provided directory "/usr/local/vufind/httpd/local/cache/objects" does not exist in /usr/local/vufind/httpd/vendor/ocramius/proxy-manager/src/ProxyManager/Exception/InvalidProxyDirectoryException.php:35\nStack trace:\n#0 /usr/local/vufind/httpd/vendor/ocramius/proxy-manager/src/ProxyManager/FileLocator/FileLocator.php(48): ProxyManager\\Exception\\InvalidProxyDirectoryException::proxyDirectoryNotFound('/usr/local/vufi...')\n#1 /usr/local/vufind/httpd/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php(96): ProxyManager\\FileLocator\\FileLocator->__construct('/usr/local/vufi...')\n#2 /usr/local/vufind/httpd/module/VuFind/src/VuFind/Service/ProxyConfigFactory.php(69): ProxyManager\\Configuration->getProxyAutoloader()\n#3 /usr/local/vufind/httpd/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(764): VuFind\\Service\\ProxyConfigFactory->__invoke(Object(Zend\\ServiceManager\\ServiceManager), 'ProxyManager\\\\Co...', NULL)\n#4 /usr/local/vufi in /usr/local/vufind/httpd/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 771

**Comment by liowalter** [comment]
ansible process was overwriting apache configuration
